[2023-11-24T16:40:12.230+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: covid_data_dag_postgres_plis.ingestion.store_government_measures manual__2023-11-23T19:18:14.833196+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-11-24T16:40:12.482+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
