[2023-11-15T15:49:00.155+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres.download_location_data manual__2023-11-15T15:48:42.739941+00:00 [queued]>
[2023-11-15T15:49:00.388+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres.download_location_data manual__2023-11-15T15:48:42.739941+00:00 [queued]>
[2023-11-15T15:49:00.403+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-15T15:49:01.243+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): download_location_data> on 2023-11-15 15:48:42.739941+00:00
[2023-11-15T15:49:01.307+0000] {standard_task_runner.py:57} INFO - Started process 929 to run task
[2023-11-15T15:49:01.372+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres', 'download_location_data', 'manual__2023-11-15T15:48:42.739941+00:00', '--job-id', '961', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpbrfir4s1']
[2023-11-15T15:49:01.468+0000] {standard_task_runner.py:85} INFO - Job 961: Subtask download_location_data
[2023-11-15T15:50:16.894+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T15:50:17.546+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
